fix: docker build

diff --git a/dockerfiles/Dockerfile.debian b/dockerfiles/Dockerfile.debian
--- a/dockerfiles/Dockerfile.debian
+++ b/dockerfiles/Dockerfile.debian
@@ -13,12 +13,21 @@ RUN if [ "${TARGETPLATFORM}" = "linux/arm64" ]; then \
     exit 1; \
     fi
 
-RUN apt update && apt install -y curl && \
+# hadolint ignore=DL3008
+RUN apt-get update && apt-get install --no-install-recommends -y curl ca-certificates && \
     apt-get clean && \
     rm -rf /var/lib/apt/lists/*
 
 WORKDIR /usr/local/bin
-RUN curl -L "https://github.com/biomejs/biome/releases/download/cli%2Fv${BIOME_VERSION}/biome-linux-${ARCH}" -o biome && \
+RUN if [ "${TARGETPLATFORM}" = "linux/arm64" ]; then \
+    ARCH=arm64; \
+    elif [ "${TARGETPLATFORM}" = "linux/amd64" ]; then \
+    ARCH=x64; \
+    else \
+    echo "Error: Unsupported architecture ${TARGETPLATFORM}" >&2; \
+    exit 1; \
+    fi && \
+    curl -L "https://github.com/biomejs/biome/releases/download/cli%2Fv${BIOME_VERSION}/biome-linux-${ARCH}-musl" -o biome && \
     chmod +x biome
 
 WORKDIR /data
