feat: multi arch dockerfiles

diff --git a/dockerfiles/Dockerfile.alpine b/dockerfiles/Dockerfile.alpine
--- a/dockerfiles/Dockerfile.alpine
+++ b/dockerfiles/Dockerfile.alpine
@@ -1,9 +1,15 @@
 FROM alpine:3.20
 
+ARG ARCH=x64
 ARG BIOME_VERSION=1.7.3
 
+RUN if [ "${ARCH}" != "x64" ] && [ "${ARCH}" != "arm64" ]; then \
+    echo "Error: ARCH must be x64 or arm64" >&2; \
+    exit 1; \
+    fi
+
 WORKDIR /usr/local/bin
-RUN wget -O biome "https://github.com/biomejs/biome/releases/download/cli%2Fv${BIOME_VERSION}/biome-linux-x64-musl" && \
+RUN wget -O biome "https://github.com/biomejs/biome/releases/download/cli%2Fv${BIOME_VERSION}/biome-linux-${ARCH}-musl" && \
     chmod +x biome
 
 WORKDIR /data
diff --git a/dockerfiles/Dockerfile.debian b/dockerfiles/Dockerfile.debian
--- a/dockerfiles/Dockerfile.debian
+++ b/dockerfiles/Dockerfile.debian
@@ -1,13 +1,19 @@
 FROM debian:stable-slim
 
+ARG ARCH=x64
 ARG BIOME_VERSION=1.7.3
 
-RUN apt-get update && apt-get install -y curl && \
-    apt get clean && \
+RUN if [ "${ARCH}" != "x64" ] && [ "${ARCH}" != "arm64" ]; then \
+    echo "Error: ARCH must be x64 or arm64" >&2; \
+    exit 1; \
+    fi
+
+RUN apt update && apt install -y curl && \
+    apt-get clean && \
     rm -rf /var/lib/apt/lists/*
 
 WORKDIR /usr/local/bin
-RUN curl -L "https://github.com/biomejs/biome/releases/download/cli%2Fv${BIOME_VERSION}/biome-linux-x64" -o biome && \
+RUN curl -L "https://github.com/biomejs/biome/releases/download/cli%2Fv${BIOME_VERSION}/biome-linux-${ARCH}" -o biome && \
     chmod +x biome
 
 WORKDIR /data
