feat: multi arch dockerfiles (#3)
* feat: multi arch dockerfiles

* feat: multi arch support

* fix: ci

* fix: target platform

* ci: use hadolint action

* fix: dockerfile ci

* fix: docker build

* chore: clean

diff --git a/dockerfiles/Dockerfile.alpine b/dockerfiles/Dockerfile.alpine
--- a/dockerfiles/Dockerfile.alpine
+++ b/dockerfiles/Dockerfile.alpine
@@ -1,9 +1,19 @@
 FROM alpine:3.20
 
+ARG TARGETPLATFORM
+ARG ARCH
 ARG BIOME_VERSION=1.7.3
 
 WORKDIR /usr/local/bin
-RUN wget -O biome "https://github.com/biomejs/biome/releases/download/cli%2Fv${BIOME_VERSION}/biome-linux-x64-musl" && \
+RUN if [ "${TARGETPLATFORM}" = "linux/arm64" ]; then \
+    ARCH=arm64; \
+    elif [ "${TARGETPLATFORM}" = "linux/amd64" ]; then \
+    ARCH=x64; \
+    else \
+    echo "Error: Unsupported architecture ${TARGETPLATFORM}" >&2; \
+    exit 1; \
+    fi && \
+    wget -qO biome "https://github.com/biomejs/biome/releases/download/cli%2Fv${BIOME_VERSION}/biome-linux-${ARCH}-musl" && \
     chmod +x biome
 
 WORKDIR /data
